name: Lambda CICD

on:
  push:
    branches:
    - master
    - staging
    - develop

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest # just use this and stop overthinking
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:  
          node-version: '14'
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci 
      - name: deploy
        run: |
          zip -j deploy.zip ./* #--> Zip the Code As we know lambda function accept the zip file.
          aws lambda update-function-code --function-name=test --zip-file=fileb://deploy.zip
